In [1]:
import os
import shutil
import zipfile
import patoolib
from pyunpack import Archive

In [30]:
sf.available_formats()

{'AIFF': 'AIFF (Apple/SGI)',
 'AU': 'AU (Sun/NeXT)',
 'AVR': 'AVR (Audio Visual Research)',
 'CAF': 'CAF (Apple Core Audio File)',
 'FLAC': 'FLAC (Free Lossless Audio Codec)',
 'HTK': 'HTK (HMM Tool Kit)',
 'SVX': 'IFF (Amiga IFF/SVX8/SV16)',
 'MAT4': 'MAT4 (GNU Octave 2.0 / Matlab 4.2)',
 'MAT5': 'MAT5 (GNU Octave 2.1 / Matlab 5.0)',
 'MPC2K': 'MPC (Akai MPC 2k)',
 'OGG': 'OGG (OGG Container format)',
 'PAF': 'PAF (Ensoniq PARIS)',
 'PVF': 'PVF (Portable Voice Format)',
 'RAW': 'RAW (header-less)',
 'RF64': 'RF64 (RIFF 64)',
 'SD2': 'SD2 (Sound Designer II)',
 'SDS': 'SDS (Midi Sample Dump Standard)',
 'IRCAM': 'SF (Berkeley/IRCAM/CARL)',
 'VOC': 'VOC (Creative Labs)',
 'W64': 'W64 (SoundFoundry WAVE 64)',
 'WAV': 'WAV (Microsoft)',
 'NIST': 'WAV (NIST Sphere)',
 'WAVEX': 'WAVEX (Microsoft)',
 'WVE': 'WVE (Psion Series 3)',
 'XI': 'XI (FastTracker 2)'}

In [2]:
os.chdir('C:\\Users\\OMEN\\Desktop\\project_ids\\DS Semester Project')
os.getcwd()

'C:\\Users\\OMEN\\Desktop\\project_ids\\DS Semester Project'

In [3]:
fil=os.listdir()
file=[]
for f in fil:
    file.append(f[:])
file

['A.C', 'Bulb', 'Gaana', 'T.V']

In [4]:
import librosa
import soundfile as sf
import numpy as np
import librosa.display
import pandas as pd


#os.chdir('..')
name=[]
mfcc=[]
info=[]

for f in file:
    os.chdir(f)
    x=os.listdir()
    for i in x:
        name.append(f)
        y,sr=librosa.load(os.getcwd()+'\\'+i)
        mfcc1 = librosa.feature.mfcc(y, sr=sr)
        audio=mfcc1.flatten()
        audio=np.pad(audio,(0,8000-len(audio)),'constant')
        info.append(audio)
        mfcc.append(mfcc1)
        
    os.chdir('..')

In [5]:
df=pd.DataFrame({'Name':name,'MFCC':mfcc})
df

Name                                               MFCC
0     A.C  [[-509.6676, -509.6676, -509.6676, -509.6676, ...
1     A.C  [[-665.47974, -665.47974, -665.47974, -665.479...
2     A.C  [[-539.48883, -539.48883, -539.10583, -537.239...
3     A.C  [[-592.77625, -568.8856, -583.0057, -598.29297...
4     A.C  [[-601.29865, -600.59064, -601.9574, -592.5972...
...   ...                                                ...
5152  T.V  [[-529.7096, -527.4151, -529.144, -528.17236, ...
5153  T.V  [[-464.78415, -460.64105, -453.20917, -464.673...
5154  T.V  [[-464.78415, -460.64105, -453.20917, -464.673...
5155  T.V  [[-527.009, -527.4413, -526.5463, -523.66284, ...
5156  T.V  [[-510.37036, -509.6617, -512.70636, -520.0435...

[5157 rows x 2 columns]

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Label']=le.fit_transform(df.Name)
df

Name                                               MFCC  Label
0     A.C  [[-509.6676, -509.6676, -509.6676, -509.6676, ...      0
1     A.C  [[-665.47974, -665.47974, -665.47974, -665.479...      0
2     A.C  [[-539.48883, -539.48883, -539.10583, -537.239...      0
3     A.C  [[-592.77625, -568.8856, -583.0057, -598.29297...      0
4     A.C  [[-601.29865, -600.59064, -601.9574, -592.5972...      0
...   ...                                                ...    ...
5152  T.V  [[-529.7096, -527.4151, -529.144, -528.17236, ...      3
5153  T.V  [[-464.78415, -460.64105, -453.20917, -464.673...      3
5154  T.V  [[-464.78415, -460.64105, -453.20917, -464.673...      3
5155  T.V  [[-527.009, -527.4413, -526.5463, -523.66284, ...      3
5156  T.V  [[-510.37036, -509.6617, -512.70636, -520.0435...      3

[5157 rows x 3 columns]

In [7]:
information=np.array(info)
information1=pd.DataFrame(information)
information1

0           1           2           3           4           5     \
0    -509.667603 -509.667603 -509.667603 -509.667603 -509.667603 -506.151886   
1    -665.479736 -665.479736 -665.479736 -665.479736 -665.479736 -665.479736   
2    -539.488831 -539.488831 -539.105835 -537.239502 -536.090698 -533.398193   
3    -592.776245 -568.885620 -583.005676 -598.292969 -599.210999 -601.380737   
4    -601.298645 -600.590637 -601.957397 -592.597229 -579.640259 -590.496582   
...          ...         ...         ...         ...         ...         ...   
5152 -529.709595 -527.415100 -529.143982 -528.172363 -528.828857 -530.919373   
5153 -464.784149 -460.641052 -453.209167 -464.673676 -470.122131 -471.715820   
5154 -464.784149 -460.641052 -453.209167 -464.673676 -470.122131 -471.715820   
5155 -527.008972 -527.441284 -526.546326 -523.662842 -521.486084 -524.662842   
5156 -510.370361 -509.661713 -512.706360 -520.043518 -515.890564 -518.133484   

            6           7           8           9     ...  7990  7991  7992  \
0    -487.012634 -481.628906 -484.005524 -486.720398  ...   0.0   0.0   0.0   
1    -665.479736 -665.479736 -665.479736 -665.479736  ...   0.0   0.0   0.0   
2    -531.821228 -528.569580 -527.364868 -514.489807  ...   0.0   0.0   0.0   
3    -603.831604 -603.557312 -602.470093 -602.926270  ...   0.0   0.0   0.0   
4    -602.195190 -602.778687 -603.145813 -602.955750  ...   0.0   0.0   0.0   
...          ...         ...         ...         ...  ...   ...   ...   ...   
5152 -531.886475 -530.017700 -531.164490 -532.587097  ...   0.0   0.0   0.0   
5153 -477.704041 -471.946808 -484.015198 -506.291992  ...   0.0   0.0   0.0   
5154 -477.704041 -471.946808 -484.015198 -506.291992  ...   0.0   0.0   0.0   
5155 -527.098511 -522.540039 -523.548584 -526.251709  ...   0.0   0.0   0.0   
5156 -522.797302 -520.182617 -518.880188 -524.791016  ...   0.0   0.0   0.0   

      7993  7994  7995  7996  7997  7998  7999  
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...  
5152   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5153   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5154   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5155   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5156   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5157 rows x 8000 columns]

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [9]:
x=information1
y=df["Label"]
print('Shape of x=',x.shape)
print('Shape of y=',y.shape)

Shape of x= (5157, 8000)
Shape of y= (5157,)


In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=51)
print('Shape of x_train= ',x_train.shape)
print('Shape of y_train= ',y_train.shape)
print('Shape of x_test= ',x_test.shape)
print('Shape of y_test= ',y_test.shape)

Shape of x_train=  (4125, 8000)
Shape of y_train=  (4125,)
Shape of x_test=  (1032, 8000)
Shape of y_test=  (1032,)


In [11]:
from sklearn.neighbors import KNeighborsClassifier
clf=KNeighborsClassifier()
clf.fit(x_train,y_train)
pred=clf.predict(x_test)
clf.score(x_test,y_test)

0.6143410852713178

In [12]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report 
print ("Accuracy : " , accuracy_score(y_test,pred)*100)  
print("Report : \n", classification_report(y_test, pred))
print("F1 Score : ",f1_score(y_test, pred, average='macro')*100)

Accuracy :  61.434108527131784
Report : 
               precision    recall  f1-score   support

           0       0.38      0.32      0.35       109
           1       0.67      0.81      0.73       262
           2       0.57      0.65      0.61       280
           3       0.67      0.54      0.60       381

    accuracy                           0.61      1032
   macro avg       0.57      0.58      0.57      1032
weighted avg       0.61      0.61      0.61      1032

F1 Score :  57.21710341096625


In [13]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(x_train, y_train)
pred=clf.predict(x_test)
print (pred)
clf.score(x_test,y_test)
print ("Accuracy : " , accuracy_score(y_test,pred)*100)  
print("Report : \n", classification_report(y_test, pred))
print("F1 Score : ",f1_score(y_test, pred, average='macro')*100)

[1 2 2 ... 3 3 3]
Accuracy :  57.751937984496124
Report : 
               precision    recall  f1-score   support

           0       0.30      0.28      0.29       109
           1       0.58      0.55      0.57       262
           2       0.68      0.86      0.76       280
           3       0.55      0.47      0.51       381

    accuracy                           0.58      1032
   macro avg       0.53      0.54      0.53      1032
weighted avg       0.57      0.58      0.57      1032

F1 Score :  53.13676786752488


In [14]:
#from:https://www.youtube.com/watch?v=0Lt9w-BxKFQ
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf = clf.fit(x_train, y_train)
pred=clf.predict(x_test)
print (pred)
clf.score(x_test,y_test)
print ("Accuracy : " , accuracy_score(y_test,pred)*100)  
print("Report : \n", classification_report(y_test, pred))
print("F1 Score : ",f1_score(y_test, pred, average='macro')*100)

[3 3 3 ... 3 3 3]
Accuracy :  40.60077519379845
Report : 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       109
           1       0.59      0.16      0.25       262
           2       0.36      0.24      0.29       280
           3       0.40      0.81      0.54       381

    accuracy                           0.41      1032
   macro avg       0.34      0.30      0.27      1032
weighted avg       0.40      0.41      0.34      1032

F1 Score :  26.89966726369296


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
from sklearn.neural_network import MLPClassifier

In [19]:
#from:https://www.youtube.com/watch?v=0Lt9w-BxKFQ
mlpc=MLPClassifier(hidden_layer_sizes=(11,11,11),max_iter=500)
mlpc.fit(x_train, y_train)
pred=mlpc.predict(x_test)
mlpc.score(x_test,y_test)
print ("Accuracy : " , accuracy_score(y_test,pred)*100)  
print("Report : \n", classification_report(y_test, pred))
print("F1 Score : ",f1_score(y_test, pred, average='macro')*100)

Accuracy :  40.310077519379846
Report : 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       109
           1       0.62      0.13      0.21       262
           2       0.76      0.10      0.18       280
           3       0.38      0.93      0.54       381

    accuracy                           0.40      1032
   macro avg       0.44      0.29      0.23      1032
weighted avg       0.50      0.40      0.30      1032

F1 Score :  23.178120007546145


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [23]:
#from:https://www.youtube.com/watch?v=0Lt9w-BxKFQ
from sklearn.svm import SVC
clf = svm.SVC()
clf = clf.fit(x_train, y_train)
pred=clf.predict(x_test)
print (pred)
clf.score(x_test,y_test)
print ("Accuracy : " , accuracy_score(y_test,pred)*100)  
print("Report : \n", classification_report(y_test, pred))
print("F1 Score : ",f1_score(y_test, pred, average='macro')*100)

<IPython.core.display.Javascript object>

[1 2 2 ... 3 3 3]
Accuracy :  56.87984496124031
Report : 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       109
           1       0.66      0.58      0.62       262
           2       0.53      0.56      0.55       280
           3       0.55      0.72      0.63       381

    accuracy                           0.57      1032
   macro avg       0.44      0.47      0.45      1032
weighted avg       0.51      0.57      0.54      1032

F1 Score :  44.79990853211968
